import keyMirror from "keymirror";


export default keyMirror({
  EXPEDITION_REGISTER: null,
  EXPEDITION_REGISTER_FAILED: null,
  EXPEDITION_GET: null,
  EXPEDITION_GET_FAILED: null,
  EXPEDITION_GET_WAYPOINT: null,
  EXPEDITION_GET_WAYPOINT_FAILED: null,
  EXPEDITION_GET_REGISTRATIONS: null,
  EXPEDITION_GET_REGISTRATIONS_FAILED: null,
  EXPEDITION_DEREGISTER: null,
  EXPEDITION_DEREGISTER_FAILED: null
});
